cnblog/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.views.static import serve
from cnblog import settings
from django.urls import include
from blog import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login,name='log'),
    path('index/', views.index),
    path('logout/', views.logout),
    re_path('^$', views.index),
    path('register/', views.register),
    path('get_validCode_img/', views.get_validCode_img),
    # path('calendar/', views.calendar),


    # 后台管理url
    re_path('cn_backend/$',views.cn_backend),
    re_path('cn_backend/add_article/$',views.add_article),
    # 后台文本编辑器上传功能
    path('upload/',views.upload),
    re_path(r"^article/(\d+)/delete", views.article_delete),
    re_path(r"^article/(\d+)/edit", views.article_edit),




    # 点赞
    path('digg/',views.digg),

    path("comment/", views.comment),
    # 获取评论树相关数据
    path("get_comment_tree/", views.get_comment_tree),



    # media
    re_path(r'media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),

    # 文章详情页
    # re_path('(?P<username>\w)/(?P<article_id>\d+)$',views.article_detail),
    re_path('^(?P<username>\w+)/articles/(?P<article_id>\d+)$', views.article_detail),

    # 关于个人站点的url
    re_path("^(?P<username>\w+)/$", views.home_site),  # home_site(reqeust,username="yuan")
    #个人站点下的跳转
    re_path('^(?P<username>\w+)/(?P<condition>tag|category|archive)/(?P<param>.*)/$', views.home_site),
    # home_site(reqeust,username="yuan",condition='tag',param='python')

]

blog/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User, AbstractUser


class UserInfo(AbstractUser):
    """
    用户信息
    """
    nid = models.AutoField(primary_key=True)
    telephone = models.CharField(max_length=11, null=True, unique=True)
    avatar = models.FileField(upload_to='avatars/', default="/avatars/default.png")
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    blog = models.OneToOneField(to='Blog', to_field='nid', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.username


class Blog(models.Model):
    """
    博客信息表（站点表）
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site_name = models.CharField(verbose_name='站点名称', max_length=64)
    theme = models.CharField(verbose_name='博客主题', max_length=32)

    def __str__(self):
        return self.title


class Category(models.Model):
    """
    博主个人文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Article(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=255, verbose_name='文章描述')
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    content = models.TextField()

    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)

    user = models.ForeignKey(verbose_name='作者', to='UserInfo', to_field='nid', on_delete=models.CASCADE)
    category = models.ForeignKey(to='Category', to_field='nid', null=True, on_delete=models.CASCADE)
    tags = models.ManyToManyField(
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )

    def __str__(self):
        return self.title


class Article2Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid', on_delete=models.CASCADE)
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid', on_delete=models.CASCADE)

    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]

    def __str__(self):
        v = self.article.title + "---" + self.tag.title
        return v


class ArticleUpDown(models.Model):
    """
    点赞表
    """

    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey('UserInfo', null=True, on_delete=models.CASCADE)
    article = models.ForeignKey("Article", null=True, on_delete=models.CASCADE)
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = [
            ('article', 'user'),
        ]


class Comment(models.Model):
    """

    评论表

    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid', on_delete=models.CASCADE)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid', on_delete=models.CASCADE)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    content = models.CharField(verbose_name='评论内容', max_length=255)

    parent_comment = models.ForeignKey("self", null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

templates/article_detail.html
{% extends "base.html" %}

{% block content %}
    {% csrf_token %}

    <div class="article_info">
        <h3 class="text-center title">{{ article_obj.title }}</h3>
        <div class="cont">
            {{ article_obj.content|safe }}
        </div>
{#        博客园的点赞样式  ----#}
        <div class="">
            <div id="div_digg">
{#                点赞#}
                <div class="diggit action">
                    <span class="diggnum" id="digg_count">{{ article_obj.up_count }}</span>
                </div>
{#                反对#}
                <div class="buryit action">
                    <span class="burynum" id="bury_count">{{ article_obj.down_count }}</span>
                </div>
                <div class="clear"></div>
                <hr>
                <hr>
                <div class="diggword" id="digg_tips" style="color: red;" ></div>
            </div>
        </div>
    </div>
    <hr>
{#    点赞#}
      <script>
         $("#div_digg .action").click(function () {
                var is_up = $(this).hasClass("diggit");


                $obj = $(this).children("span");

                $.ajax({
                    url: "/digg/",
                    type: "post",
                    data: {
                        "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val(),
                        "is_up": is_up,
                        "article_id": "{{ article_obj.pk }}",
                    },
                    success: function (data) {
                        console.log(data);

                        if (data.state) {
                            var val = parseInt($obj.text());
                            $obj.text(val + 1);
                        }
                        else {
                            var val2 = data.handled ? "您已经推荐过!" : "您已经反对过!";
                            $("#digg_tips").html(val2);

                            setTimeout(function () {
                                $("#digg_tips").html("")
                            }, 1000)

                        }

                    }
                })
            });
    {#评论请求#}
        $('.comment_btn').click(function () {
            var content = $("#comment_content").val();
            $.ajax({
                url:'/comment/',
                type: 'post',
                data: {  "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val(),
                  "article_id": "{{ article_obj.pk }}",
                        "content": content,
                        pid: pid},
                success:function (data) {
                    console.log(data)
                }
            })
        })

    </script>



{#    评论#}
    <div class="comments list-group">
        <p class="tree_btn" style="color: #c7254e">评论树</p>
        <div class="comment_tree">
{#            <div comment_id="'1">#}
{#                <span></span>#}
{#            </div>#}
{#            <div comment_id="'2">#}
{#                <span></span>#}
{#            </div>#}
{#            <div comment_id="'3">#}
{#                <span></span>#}
{#            </div>#}

        </div>
      {#-------评论树-------#}
        <script>


                 $.ajax({
                        url: "/get_comment_tree/",
                        type: "get",
                        data: {
                            article_id: "{{ article_obj.pk }}"
                        },
                        success: function (comment_list) {
                            console.log(comment_list);

                            $.each(comment_list, function (index, comment_object) {

                                var pk = comment_object.pk;
                                var content = comment_object.content;
                                var parent_comment_id = comment_object.parent_comment_id;
                                var s = '<div class="comment_item" comment_id=' + pk + '><span>' + content + '</span></div>';

                                if (!parent_comment_id) {

                                    $(".comment_tree").append(s);
                                } else {
                                    $("[comment_id=" + parent_comment_id + "]").append(s);
                                }
                            })
                        }
                    })



            </script>


        <p style="color: #c7254e">评论列表</p>
        <ul class="list-group comment_list">
            {% for comment in comment_list %}
                <li class="list-group-item">
                    <div>
                        <a href=""># {{ forloop.counter }}楼</a> &nbsp;&nbsp;
                        <span>{{ comment.create_time|date:"Y-m-d H:i" }}</span>&nbsp;&nbsp;
                        <a href=""><span>{{ comment.user.username }}</span></a>
                        <a class="pull-right reply_btn" username="{{ comment.user.username }}"
                           comment_pk="{{ comment.pk }}">回复</a>
                    </div>

                    {% if comment.parent_comment_id %}
                        <div class="pid_info well">
                            <p>
                                {{ comment.parent_comment.user.username }}: {{ comment.parent_comment.content }}
                            </p>
                        </div>
                    {% endif %}
                    <div class="comment_con">
                        <p>{{ comment.content }}</p>
                    </div>
                </li>
            {% endfor %}
        </ul>
        <p style="color: #c7254e">发表评论</p>
        <p>昵称：<input type="text" id="tbCommentAuthor" class="author" disabled="disabled" size="50"
                     value="{{ request.user.username }}">
        </p>
        <p>评论内容:</p>
        <textarea name="" id="comment_content" cols="60" rows="10"></textarea>
        <p>
            <button class="btn btn-default comment_btn btn-success">提交评论</button>
        </p>
    </div>

    <script>

        var pid='';
        $('.comment_btn').click(function () {
            {#根评论#}
            {#var pid='';#}
            var content=$('#comment_content').val();

            if(pid){
                var index=content.indexOf('\n');
                content=content.slice(index+1)
            }
            $.ajax({
                url:'/comment/',
                type:'post',
                data:{  "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val(),
                'article_id':'{{ article_obj.pk }}','content':content ,'pid':pid},
                success:function (data) {
                    console.log(data);

                    var create_time = data.create_time;
                    var username=data.username;
                    var content=data.content;

                    // 构建标签字符串 es6语法
                     var s = `
                           <li class="list-group-item">
                              <div>

                                  <span>${create_time}</span>&nbsp;&nbsp;
                                  <a href=""><span>${username}</span></a>

                              </div>
                              <div class="comment_con">
                                  <p>${content}</p>
                              </div>

                            </li>`;

                        $("ul.comment_list").append(s);



                    // 传回数据后，清空评论框中的内容
                    $('#comment_content').val('');
                    pid=''
                }

            })
        });

        // 回复按钮事件

        $('.reply_btn').click(function () {
            $('#comment_content').focus();
            // 找父评论
            var val='@'+$(this).attr('username')+'\n';
            $('#comment_content').val(val)
            pid=$(this).attr('comment_pk')
        })

    </script>



{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <style>
        * {
            margin: 0;
            padding: 0
        }

        .header {
            width: 100%;
            height: 60px;
            background-color: #369
        }

        .header .title {
            font-size: 18px;
            font-weight: 100;
            line-height: 60px;
            color: white;
            margin-left: 15px
        }

        .backend {
            float: right;
            margin-right: 15px;
            color: white;
            text-decoration: none;
        }


.article_info .title{
   margin-bottom: 100px;
}

        {% block css %}

        {% endblock %}
    </style>

    <link rel="stylesheet" href="/static/blog/bootstrap-3.3.7/css/bootstrap.css">

{#    在base引入home_site 和 article_datail的样式#}
    <link rel="stylesheet" href="/static/css/article_detail.css" >
    <link rel="stylesheet" href="/static/css/home_site.css" >
    <script src="/static/JS/jquery-3.2.1.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="/static/blog/bootstrap-3.3.7/js/bootstrap.min.js"></script>
{#    <link rel="stylesheet" href="/static/css/calendar.css">#}
    <script src="/static/JS/calendar.js"></script>


</head>
<body>
<div class="header navbar ">
    <div class="content">
        <p class="title">
            <span>{{ blog.title }}</span>
            <a href="/cn_backend/" class="backend">管理</a>
        </p>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-3">

            <div class="panel panel-warning">
                <div class="panel-heading">我的标签</div>
                <div class="panel-body">
                    {% for tag in tag_list %}
                        <p><a href="/{{ username }}/tag/{{ tag.0 }}">{{ tag.0 }}({{ tag.1 }})</a></p>
                    {% endfor %}
                </div>
            </div>
            <div class="panel panel-danger">
                <div class="panel-heading">随笔分类</div>
                <div class="panel-body">
                    {% for cate in cate_list %}
                        <p><a href="/{{ username }}/category/{{ cate.0 }}">{{ cate.0 }}({{ cate.1 }})</a></p>
                    {% endfor %}
                </div>
            </div>

            <div class="panel panel-success">
                <div class="panel-heading">随笔归档</div>
                <div class="panel-body">
                    {% for date in date_list %}
                        <p><a href="/{{ username }}/archive/{{ date.0 }}">{{ date.0 }}({{ date.1 }})</a></p>
                    {% endfor %}
                </div>
            </div>

        </div>
        <div class="col-md-9">
           {% block  content %}

            {% endblock %}
        </div>
    </div>
</div>

</body>
</html>

templates/classification.html
<div>
    <div class="panel panel-warning">
        <div class="panel-heading">我的标签</div>
        <div class="panel-body">
            {% for tag in tag_list %}
                <p><a href="/{{ username }}/tag/{{ tag.0 }}">{{ tag.0 }}({{ tag.1 }})</a></p>
            {% endfor %}

        </div>
    </div>

    <div class="panel panel-danger">
        <div class="panel-heading">随笔分类</div>
        <div class="panel-body">
            {% for cate in cate_list %}
                <p><a href="/{{ username }}/category/{{ cate.0 }}">{{ cate.0 }}({{ cate.1 }})</a></p>
            {% endfor %}
        </div>
    </div>

    <div class="panel panel-success">
        <div class="panel-heading">随笔归档</div>
        <div class="panel-body">
            {% for date in date_list %}
                <p><a href="/{{ username }}/archive/{{ date.0 }}">{{ date.0 }}({{ date.1 }})</a></p>
            {% endfor %}
        </div>
    </div>
</div>

templates/home_site.html
{% extends  'base.html'%}
{% block css %}

{% endblock %}

{% block content %}

     {#            文章样式#}
            <div class="article_list">
                   {% for article in article_list %}
                    <div class="article-item clearfix">
                        <h4><a href="/{{ article.user.username }}/articles/{{ article.pk }}">{{ article.title }}</a></h4>
                        <div class="article-desc">
                            {{ article.desc }}
                        </div>
                        <div class="small pub_info pull-right">
                            <span>发布于 &nbsp;&nbsp;{{ article.create_time|date:"Y-m-d H:i" }}</span>&nbsp;&nbsp;
                            <span class="glyphicon glyphicon-comment"></span>评论({{ article.comment_count }})&nbsp;&nbsp;
                            <span class="glyphicon glyphicon-thumbs-up"></span>点赞({{ article.up_count }})&nbsp;&nbsp;
                        </div>
                    </div>
                    <hr>
                    {% endfor %}
            </div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/blog/bootstrap-3.3.7/css/bootstrap.css">


</head>
<body>



   <div class="container">
       <div class="row">
           <div class="col-md-6 col-md-offset-3">
               <form>
                   {% csrf_token %}

                       <h3 class="text-primary text-center">登录页面</h3>
                       <div class="form-group   ">
                           <label for="username">username</label>
                           <input type="text" class="form-control " placeholder="username" id="username">
                       </div>
                       <div class="form-group ">
                           <label for="password">Password</label>
                           <input type="password" class="form-control " id="password" placeholder="Password">
                       </div>
                        <div class="form-group">
                            <label for="id_valid_code_str">验证码</label>
                            <div class="row ">
                                <div class="col-md-6">
                                    <input type="text" id="id_valid_code_str" class="form-control">
                                </div>
                                <div class="col-md-6">
                                    <img src="/get_validCode_img/"  id="id_valid_code_img" width="270" height="34" title="验证码" alt="">
                                </div>
                            </div>
                         </div>
                       <div class="form-group">
                           <div class="row">
                               <div class="col-md-6">
                                   <input type="button" class="btn btn-default login-btn pull-left" value="登录"><span
                                       class="error"></span>
                               </div>
                               <div class="col-md-6">
                                   <a href="/register/" class="btn btn-success pull-right">注册</a>
                               </div>
                           </div>
                       </div>
               </form>
            </div>
       </div>

   </div>

<script type="text/javascript" src="/static/JS/jquery-3.2.1.min.js"></script>

<script type="text/javascript">
  //刷新验证码
    $(function () {
        $("#id_valid_code_img").click(function () {
            $(this)[0].src+="?"
        })
    });


    // 登录验证
    $('.login-btn').click(function () {
        $.ajax(
            {
                url:'',
               type:'post',
               data:{user:$('#username').val(),pwd:$('#password').val(),valid_code:$('#id_valid_code_str').val(),
{#                   {% csrf_token %}#}
               csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()},

                success:function (data) {
                    console.log(data);
                    if(data.user){
                        location.href='/index'
                    }
                    else {
                        $('.error').text(data.msg).css({'color':'red','margin-left':'10px'})
                        setTimeout(function () {
                            $('.error').text('')
                        },1000)
                    }
                }
            })

    })
</script>


</body>


</html>

templates/not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/blog/bootstrap-3.3.7/css/bootstrap.css">
</head>
<body>


<div class="container" style="margin-top: 100px">
    <div class="text-center">
        <a href="http://www.cnblogs.com/"><img src="/static/img/logo_small.gif" alt="cnblogs"></a>
        <p><b>404.</b> 抱歉! 您访问的资源不存在!</p>
        <p class="d">请确认您输入的网址是否正确，如果问题持续存在，请发邮件至 404042726@qq.com 与 <strong style="font-size: 28px">老村长</strong> 联系。</p>
        <p><a href="/">返回网站首页</a></p>

    </div>
</div>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/blog/bootstrap-3.3.7/css/bootstrap.css">

    <style type="text/css">
        #avatar{display: none}
        #avatar_img{margin-left: 20px}
         .error {
            color: red;
        }
    </style>
</head>
<body>



   <div class="container">
       <div class="row">

           <div class="col-md-6 col-md-offset-3">
            <h3 class="text-primary text-center">注册页面</h3>
           <hr>
               <form id="form">
                   {% csrf_token %}
                   {% for field in form %}
                       <div class="form-group">
                           <label for="{{ field.auto_id }}">{{ field.label }}</label>
                           {{ field }} <span class="error pull-right"></span>
                       </div>
                   {% endfor %}
{#                    上传头像功能#}
                   <div class="form-group">
                       <label for="avatar">
                           头像
                           <img id="avatar_img" width="60" height="60" src="/static/img/default.png" alt="">
                       </label>
                       <input type="file" id="avatar" name="avatar" >
                   </div>
                   <div class="form-group">
                       <div class="row">
                           <input type="button" class="btn btn-default reg_btn" value="submit"><span class="error"></span>

                       </div>
                   </div>
               </form>
            </div>
       </div>
   </div>

<script type="text/javascript" src="/static/JS/jquery-3.2.1.min.js"></script>

<script type="text/javascript">


$('#avatar').change(function () {
    // 1 获取用户选中的文件对象
    var file_obj=$(this)[0].files[0];

    // 2 获取文件路径
    var reader= new FileReader();

    reader.readAsDataURL(file_obj);
    // 3 修改img的src属性，src=文件对象的路径

    // 等图片文档加载完后才执行,,等上一步读完才执行
    reader.onload=function(){
         $('#avatar_img').attr('src',reader.result)
    }
});

    // Ajax提交数据
    {#$('.reg_btn').click(function () {#}
    {#    var formdata=new FormData();#}
    {#    formdata.append('user',$('#id_user').val());#}
    {#    formdata.append('pwd',$('#id_pwd').val());#}
    {#    formdata.append('re_pwd',$('#id_re_pwd').val());#}
    {#    formdata.append('email',$('#id_email').val());#}
    {#    formdata.append('avatar',$('#avatar')[0].files[0]);#}
    {#    formdata.append('csrfmiddlewaretoken',$("[name='csrfmiddlewaretoken']").val());#}
 // 基于Ajax提交数据

    $(".reg_btn").click(function () {
        //console.log($("#form").serializeArray());
        var formdata = new FormData();
        var request_data = $("#form").serializeArray();
        $.each(request_data, function (index, data) {
            formdata.append(data.name, data.value)
        });

        formdata.append("avatar", $("#avatar")[0].files[0]);

        $.ajax({
            url:'',
            type:'post',
            contentType:false,
            processData:false,
            data:formdata,
            success:function (data) {
                console.log(data);

                if(data.user){
                    // 注册成功
                    location.href="/login/"
                }
                else {
                     //console.log(data.msg)
                    // 清空错误信息---先清空所有--移除所有样式
                    $("span.error").html("");
                    $(".form-group").removeClass("has-error");
                    // 再把含有错误的标签 赋值，加样式--达到相应的效果
                    $.each(data.msg,function (field,error_list) {
                        console.log(field,error_list);
                        // 全局错误在视图中取出来
                        if (field=='__all__'){
                            $('#id_re_pwd').next().html(error_list[0]).parent().addClass("has-error");

                        }


                        //jQuery next() 获得匹配元素集合中每个元素紧邻的同胞元素。
                        $("#id_"+ field).next().html(error_list[0]);
                        $("#id_"+ field).parent().addClass("has-error");
                    })
                }
            }
        })
    })

</script>


</body>


</html>